### ISSUE TITLE
Maintenance Quirks and Snap's runtime error due to version conflicts with gnome42-sdk

### ISSUE THREAD

**Issue by soumyaDghosh** [CapeCrusader321/Video_Trimmer-Snap#1]
Hey, again there is a miscommunication. I have registered this snap name long ago. But, this app, doesn't able to build properly due to the fact, that it uses gi-repository which is newer than in gnome-sdk. Though, as I see you've added libgirepository from the repos, and it doesn't work, as I tested. By, this I assume, that, it builds but due to the version mismatch in run time, it fails. I hope you'll understand the point.

**Comment by soumyaDghosh** [comment]
Update: I have been able to build the snap from source. Request to keep this snap down. This snap is anyway not working. Mine is currently in the review queue.

**Comment by CapeCrusader321** [comment]
I had already took the custody of maintaining this from upstream, i have currently unlisted the snap until its fixed, if it takes longer to fix i will keep this snap private until its fixed, thanks for informing

**Comment by CapeCrusader321** [comment]
Converted to discussion --> https://github.com/CapeCrusader321/Video_Trimmer-Snap/discussions/2
